import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Finna",
  description: "Generated by Rwanda Biomedical Centre",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
          {children}
      </body>
    </html>
  );
}
